Finished refactor. Added color coding.

diff --git a/auto-xorg b/auto-xorg
--- a/auto-xorg
+++ b/auto-xorg
@@ -8,16 +8,30 @@
 #
 
 # <params>
-    declare -gr _PREFIX_ERROR="An error occurred:"
     declare -g _DISPLAY_MANAGER=$( cat /etc/X11/default-display-manager )
     declare -gr _DISPLAY_MANAGER="${_DISPLAY_MANAGER##*/}"
     declare -gr _PATH_1="/etc/X11/xorg.conf.d/"
     declare -gr _FILE_1="${_PATH_1}10-auto-xorg.conf"
 
-    # <remarks> Permanent Toggles </remarks>
+    # <summary>
+    # Color coding
+    # Reference URL: 'https://www.shellhacks.com/bash-colors'
+    # </summary>
+    declare -gr _SET_COLOR_GREEN='\033[0;32m'
+    declare -gr _SET_COLOR_RED='\033[0;31m'
+    declare -gr _SET_COLOR_YELLOW='\033[0;33m'
+    declare -gr _RESET_COLOR='\033[0m'
+
+    # <summary> Append output </summary>
+    declare -gr _PREFIX_NOTE="${_SET_COLOR_YELLOW}Note:${_RESET_COLOR}"
+    declare -gr _PREFIX_ERROR="${_SET_COLOR_YELLOW}An error occurred:${_RESET_COLOR}"
+    declare -gr _PREFIX_FAIL="${_SET_COLOR_RED}Failure:${_RESET_COLOR}"
+    declare -gr _PREFIX_PASS="${_SET_COLOR_GREEN}Success:${_RESET_COLOR}"
+
+    # <summary> Permanent Toggles </summary>
         _HAS_MATCHED_INTEL_DRIVER=true
 
-    # <remarks> File contents </remarks>
+    # <summary> File contents </summary>
         declare -ga _FILE_1_CONTENTS=(
             "#### Generated by 'portellam/auto-Xorg'"
             "# WARNING: Any modifications to this file will be modified by 'auto-Xorg'"
@@ -25,7 +39,7 @@
             "#"
         )
 
-    # <remarks> Toggles </remarks>
+    # <summary> Toggles </summary>
         declare -g _DO_RESTART_DISPLAY_MANAGER=false
         declare -g _PARSE_PCI_ORDER_BY_BUS_ID=true
         declare -g _PREFER_ANY_BRAND=true
@@ -34,7 +48,7 @@
         declare -g _PREFER_NVIDIA=false
         declare -g _PREFER_OFF_BRAND=false
 
-    # <remarks> Evaluations </remarks>
+    # <summary> Evaluations </summary>
         declare -gr _GET_PCI_ID='lspci -m | grep -Ei "vga|graphics" | cut -d " " -f 1'
         declare -gr _GET_PCI_ID_REVERSE_SORT='lspci -m | grep -Ei "vga|graphics" | cut -d " " -f 1 | sort -r'
 # </params>
@@ -65,7 +79,7 @@
 
             "-l" | "--last" )
                 _PARSE_PCI_ORDER_BY_BUS_ID=false
-                echo -e "Caution: Parsing VGA devices in reverse order." ;;
+                echo -e "$_PREFIX_NOTE Parsing VGA devices in reverse order." ;;
 
             "-r" | "--restart-display" )
                 _DO_RESTART_DISPLAY_MANAGER=true ;;
@@ -173,7 +187,7 @@
                 if [[ "$_HAS_MATCHED_INTEL_DRIVER" == true ]]; then
                     _DRIVER="modesetting"
                 else
-                    echo -e "Note: Should given parsed Intel VGA driver be invalid, replace xorg.conf with an alternate intel driver (example: 'modesetting')."
+                    echo -e "$_PREFIX_NOTE Should given parsed Intel VGA driver be invalid, replace xorg.conf with an alternate intel driver (example: 'modesetting')."
                 fi
             fi
 
@@ -206,7 +220,7 @@
                     "EndSection"
                 )
 
-                echo -e "Success: Valid VGA device found."
+                echo -e "$_PREFIX_PASS Valid VGA device found."
                 ;;
 
             * )
@@ -219,7 +233,7 @@
                     "EndSection"
                 )
 
-                echo -e "Failure: No valid VGA device found."
+                echo -e "$_PREFIX_FAIL No valid VGA device found."
                 ;;
         esac
 
@@ -245,16 +259,16 @@
 
         return 0
     }
+# </code>
 
-    # <summary> Main code block </summary>
-    function Main
-    {
-        if [[ $( whoami ) != "root" ]]; then
+# <remarks> Main </remarks>
+# <code>
+    if [[ $( whoami ) != "root" ]]; then
             echo -e "$_PREFIX_ERROR User is not sudo/root."
-            return 1
+            exit 1
         fi
 
-        if ! SetOptions "$@"; then GetUsage; return "$?"; fi
+        if ! SetOptions "$@"; then GetUsage; exit "$?"; fi
 
         # <remarks> Toggle the sort order of parse of PCI devices. </remarks>
         if "$_PARSE_PCI_ORDER_BY_BUS_ID"; then
@@ -263,24 +277,24 @@
             declare -ga _HWID_LIST=( $( eval $_GET_PCI_ID_REVERSE_SORT ) )
         fi
 
-        # <remarks> Exit early if no PCI devices are found (NOTE: more likely that the command fails, than no PCI devices exist). </remarks>
+        # <remarks> Exit early if no PCI devices are found ($_PREFIX_NOTE more likely that the command fails, than no PCI devices exist). </remarks>
         if [[ "${#_HWID_LIST[@]}" -eq 0 ]]; then
             echo -e "$_PREFIX_ERROR No PCI devices found."
-            return 1
+            exit 1
         fi
 
         # <remarks> Exit early if system directory does not exist and cannot be created. </remarks>
         if [[ ! -d "$_PATH_1" ]] \
             && [ sudo mkdir -p "$_PATH_1" ]; then
             echo -e "$_PREFIX_ERROR Failed to create directory '$_PATH_1'."
-            return 1
+            exit 1
         fi
 
         # <remarks> Exit early if existing system file cannot be overwritten. </remarks>
         if [[ -e "$_PATH_1" ]] \
             && ! sudo rm -f "$_FILE_1" &> /dev/null; then
             echo -e "$_PREFIX_ERROR Failed to delete file '$_FILE_1'."
-            return 1
+            exit 1
         fi
 
         # <remarks> Find first valid VGA driver. </remarks>
@@ -295,35 +309,28 @@
 
         if [[ "$_EXIT_CODE" -ne 0 ]]; then
             echo -e "$_PREFIX_ERROR No VGA devices found."
-            return 1
+            exit 1
         fi
 
         # <remarks> Write to file if directory exists and driver is valid. </remarks>
         if [[ ! -d "$_PATH_1" ]]; then
             echo -e "$_PREFIX_ERROR Failed to create directory '$_PATH_1'."
-            return 1
+            exit 1
         fi
 
-        SetFile || return "$?"
+        SetFile || exit "$?"
 
         # <remarks> Restart system service automatically or manually. </remarks>
         if "$_DO_RESTART_DISPLAY_MANAGER" \
             && ( ! [ sudo systemctl enable "$_FILE_2" ] \
             || ! [ sudo systemctl restart "$_FILE_2" ] ); then
             echo -e "$_PREFIX_ERROR Failed to restart system service."
-            return 1
+            exit 1
         fi
 
         if ! "$_DO_RESTART_DISPLAY_MANAGER"; then
-            echo -e "Note: You may restart the active display manager '$_DISPLAY_MANAGER'. To restart, execute 'sudo systemctl restart $_DISPLAY_MANAGER'."
+            echo -e "$_PREFIX_NOTE You may restart the active display manager '$_DISPLAY_MANAGER'.\nTo restart, execute 'sudo systemctl restart $_DISPLAY_MANAGER'."
         fi
 
-        return 0
-    }
-# </code>
-
-# <remarks> Main </remarks>
-# <code>
-    Main $@
-    exit $?
+        exit 0
 # </code>
