Worked on param names. Added references.

diff --git a/auto-xorg b/auto-xorg
--- a/auto-xorg
+++ b/auto-xorg
@@ -7,7 +7,19 @@
 # Maintainer(s):  Alex Portell <github.com/portellam>
 #
 
+# <traps>
+  trap 'catch_error' SIGINT SIGTERM ERR
+  trap 'catch_exit' EXIT
+# </traps>
+
 # <params>
+  SCRIPT_NAME="$( basename "${0}" )"
+  PREFIX_PROMPT="${SCRIPT_NAME}: "
+  PREFIX_ERROR="${PREFIX_PROMPT}An error occurred: "
+
+  SAVEIFS="${IFS}"
+  IFS=$'\n'
+
   DISPLAY_MANAGER=$( cat /etc/X11/default-display-manager )
   readonly DISPLAY_MANAGER="${DISPLAY_MANAGER##*/}"
   readonly PATH_1="/etc/X11/xorg.conf.d/"
@@ -17,51 +29,51 @@
   # Color coding
   # Reference URL: 'https://www.shellhacks.com/bash-colors'
   # </summary>
-  readonly SET_COLOR_GREEN='\033[0;32m'
-  readonly SET_COLOR_RED='\033[0;31m'
-  readonly SET_COLOR_YELLOW='\033[0;33m'
-  readonly RESET_COLOR='\033[0m'
+    readonly SET_COLOR_GREEN='\033[0;32m'
+    readonly SET_COLOR_RED='\033[0;31m'
+    readonly SET_COLOR_YELLOW='\033[0;33m'
+    readonly RESET_COLOR='\033[0m'
 
   # <summary>Append output</summary>
-  readonly PREFIX_NOTE="${SET_COLOR_YELLOW}Note:${RESET_COLOR}"
-  readonly PREFIX_ERROR="${SET_COLOR_YELLOW}An error occurred:${RESET_COLOR}"
-  readonly PREFIX_FAIL="${SET_COLOR_RED}Failure:${RESET_COLOR}"
-  readonly PREFIX_PASS="${SET_COLOR_GREEN}Success:${RESET_COLOR}"
+    readonly PREFIX_NOTE="${SET_COLOR_YELLOW}Note:${RESET_COLOR} "
+    readonly PREFIX_ERROR="${SET_COLOR_RED}An error occurred:${RESET_COLOR} "
+    readonly PREFIX_PASS="${SET_COLOR_GREEN}Success:${RESET_COLOR} "
 
   # <summary>Permanent Toggles</summary>
-  HAS_MATCHED_INTEL_DRIVER=true
+    HAS_MATCHED_INTEL_DRIVER=true
 
   # <summary>File contents</summary>
-  declare -a FILE_1_CONTENTS=(
-    "#### Generated by 'portellam/auto-Xorg'"
-    "# WARNING: Any modifications to this file will be modified by 'auto-Xorg'"
-    "# Run lspci to view hardware information."
-    "#"
-  )
+    declare -a FILE_1_CONTENTS=(
+      "#### Generated by 'portellam/auto-Xorg'"
+      "# WARNING: Any modifications to this file will be modified by 'auto-Xorg'"
+      "# Run lspci to view hardware information."
+      "#"
+    )
 
   # <summary>Toggles</summary>
-  DO_RESTART_DISPLAY_MANAGER=false
-  PARSE_PCI_ORDER_BY_BUS_ID=true
-  PREFER_ANY_BRAND=true
-  PREFER_AMD=false
-  PREFER_INTEL=false
-  PREFER_NVIDIA=false
-  PREFER_OFF_BRAND=false
-  MATCH_PROBLEM_DRIVER=false
+    DO_RESTART_DISPLAY_MANAGER=false
+    PARSE_PCI_ORDER_BY_BUS_ID=true
+    PREFER_ANY_BRAND=true
+    PREFER_AMD=false
+    PREFER_INTEL=false
+    PREFER_NVIDIA=false
+    PREFER_OFF_BRAND=false
+    MATCH_PROBLEM_DRIVER=false
 
   # <summary>Evaluations</summary>
-  readonly GET_PCI_ID='lspci -m | grep -Ei "vga|graphics" | cut -d " " -f 1'
-  readonly GET_PCI_ID_REVERSE_SORT='lspci -m | grep -Ei "vga|graphics" | cut -d " " -f 1 | sort -r'
+    readonly GET_PCI_ID='lspci -m | grep -Ei "vga|graphics" | cut -d " " -f 1'
+    readonly GET_PCI_ID_REVERSE_SORT='lspci -m | grep -Ei "vga|graphics" | cut -d " " -f 1 | sort -r'
+
+  HWID_LIST=( )
 # </params>
 
 # <functions>
   function main
   {
-    is_user_super_user
+    is_user_superuser
 
     if ! set_options "$@"; then
       print_usage
-      exit "${?}"
     fi
 
     toggle_sort_order_of_devices
@@ -72,8 +84,10 @@
     write_to_file
     restart_service
 
+    print_to_output_log "${PREFIX_PASS}Updated Xorg."
+
     if ! "${DO_RESTART_DISPLAY_MANAGER}"; then
-      echo -e "${PREFIX_NOTE} You may restart the active display manager '${DISPLAY_MANAGER}'.\nTo restart, execute 'sudo systemctl restart ${DISPLAY_MANAGER}'."
+      echo -e "${PREFIX_NOTE}You may restart the active display manager '${DISPLAY_MANAGER}'.\nTo restart, execute 'sudo systemctl restart ${DISPLAY_MANAGER}'."
     fi
 
     exit 0
@@ -88,7 +102,7 @@
 
         "-l" | "--last" )
           PARSE_PCI_ORDER_BY_BUS_ID=false
-          echo -e "${PREFIX_NOTE} Parsing VGA devices in reverse order." ;;
+          print_to_output_log "Parsing VGA devices in reverse order." ;;
 
         "-r" | "--restart-display" )
           DO_RESTART_DISPLAY_MANAGER=true ;;
@@ -127,8 +141,6 @@
 
     function print_usage
     {
-      IFS=$'\n'
-
       local -ar output=(
         "Usage: sudo bash auto-xorg [OPTION]..."
         "  Generates Xorg (video output) for the first or last parsed valid non-VFIO video (VGA) device."
@@ -149,67 +161,89 @@
       )
 
       echo -e "${output[*]}"
+      exit 0
     }
 
     function set_options
     {
       for option in "$@"; do
-        if [[ "${option}" == "" ]]; then
-          return 0
-        fi
-
+        is_string "${option}" &> /dev/null && return 0
         get_option "${option}" || return 1
       done
     }
 
+  # <summary>Clean-up</summary>
+    function reset_ifs
+    {
+      IFS="${SAVEIFS}"
+    }
+
+  # <summary>Data-type validation</summary>
+    function is_string
+    {
+      if [[ "${1}" == "" ]]; then
+        return 1
+      fi
+    }
+
   # <summary>Handlers</summary>
-    function is_user_super_user
+    function catch_error {
+      exit 255
+    }
+
+    function catch_exit {
+      reset_ifs
+      print_to_error_log "Failed to update Xorg."
+    }
+
+    function is_user_superuser
     {
       if [[ $( whoami ) != "root" ]]; then
-        echo -e "${PREFIX_ERROR} User is not sudo/root."
-        exit 1
+        print_to_error_log "User is not sudo or root."
+        return 1
       fi
+    }
+
+  # <summary>Loggers</summary>
+    function print_to_error_log
+    {
+      echo -e "${PREFIX_PROMPT}${PREFIX_ERROR}${1}" >&2
+    }
+
+    function print_to_output_log
+    {
+      echo -e "${PREFIX_PROMPT}${1}" >&1
     }
 
   function find_any_vga_device
   {
-    # <remarks>Exit early if no PCI devices are found (Note: more likely that the command fails, than no PCI devices exist).</remarks>
-    if [[ "${#_HWID_LIST[@]}" -eq 0 ]]; then
-      echo -e "${PREFIX_ERROR} No PCI devices found."
+    if [[ "${#HWID_LIST[@]}" -eq 0 ]]; then
+      print_to_error_log "No PCI devices found."
       exit 1
     fi
   }
 
   function find_first_driver
   {
-    # <remarks>Find first valid VGA driver.</remarks>
-    find_first_vga_driver
-    local -i exit_code="$?"
-
-    if [[ "${exit_code}" -ne 0 ]]; then
-      PREFER_ANY_BRAND=true
-      find_first_vga_driver
-      exit_code="$?"
-    fi
-
-    if [[ "${exit_code}" -ne 0 ]]; then
-      echo -e "${PREFIX_ERROR} No VGA devices found."
-      exit 1
-    fi
+    find_first_vga_driver && return 0
+    PREFER_ANY_BRAND=true
+    find_first_vga_driver && return 0
+    print_to_error_log "No VGA devices found."
+    exit 1
   }
 
   function find_first_vga_driver
   {
-    for _HWID in ${_HWID_LIST[@]}; do
-      _DRIVER=$( lspci -ks "$_HWID" | grep -E 'driver' | cut -d ':' -f 2 | cut -d ' ' -f 2 )
-      _TYPE=$( lspci -ms "$_HWID" | cut -d '"' -f 2 | tr '[:upper:]' '[:lower:]' )
-      _VENDOR=$( lspci -ms "$_HWID" | cut -d '"' -f 4 | tr '[:upper:]' '[:lower:]' )
-      _FUNC_ID=$( echo "$_HWID" | cut -d '.' -f 2 )
-      _PCI_ID=$( echo "$_HWID" | cut -d '.' -f 1 )
-      _PCI_ID+=":$_FUNC_ID"
+    for hwid in "${HWID_LIST[@]}"; do
+      driver=$( lspci -ks "${hwid}" | grep -E 'driver' | cut -d ':' -f 2 | cut -d ' ' -f 2 )
+      type=$( lspci -ms "${hwid}" | cut -d '"' -f 2 | tr '[:upper:]' '[:lower:]' )
+      vendor=$( lspci -ms "${hwid}" | cut -d '"' -f 4 | tr '[:upper:]' '[:lower:]' )
+      function_id=$( echo "${hwid}" | cut -d '.' -f 2 )
+      pci_id=$( echo "${hwid}" | cut -d '.' -f 1 )
+      pci_id+=":${function_id}"
 
       if match_valid_vga_device_with_driver; then
-        match_driver_and_set_xorg_write_only
+        match_driver_and_set_xorg_write_only "${driver}"
         return 0
       fi
     done
@@ -219,21 +253,24 @@
 
   function get_preferred_vendor
   {
+    local -n reference="${1}"
+    local -r vendor="${2}"
+
     case true in
-      "$PREFER_AMD" )
-        _PREFERRED_VENDOR=$( echo -e "$_VENDOR" | grep -iv 'amd|ati' | grep -iv 'corporation' ) ;;
+      "${PREFER_AMD}" )
+        reference=$( echo -e "${vendor}" | grep --ignore-case --invert-match 'amd|ati' | grep --ignore-case --invert-match 'corporation' ) ;;
 
-      "$PREFER_INTEL" )
-        _PREFERRED_VENDOR=$( echo -e "$_VENDOR" | grep -i 'intel' ) ;;
+      "${PREFER_INTEL}" )
+        reference=$( echo -e "${vendor}" | grep --ignore-case 'intel' ) ;;
 
-      "$PREFER_NVIDIA" )
-        _PREFERRED_VENDOR=$( echo -e "$_VENDOR" | grep -i 'nvidia' ) ;;
+      "${PREFER_NVIDIA}" )
+        reference=$( echo -e "${vendor}" | grep --ignore-case 'nvidia' ) ;;
 
-      "$PREFER_OFF_BRAND" )
-        _PREFERRED_VENDOR=$( echo -e "$_VENDOR" | grep -Eiv 'amd|ati|intel|nvidia' ) ;;
+      "${PPREFER_OFF_BRAND}" )
+        reference=$( echo -e "${vendor}" | grep --extended-regexp --ignore-case --invert-match 'amd|ati|intel|nvidia' ) ;;
     esac
 
-    if [[ "$_PREFERRED_VENDOR" == "" ]]; then
+    if ! is_string "${reference}" &> /dev/null; then
       return 1
     fi
   }
@@ -242,8 +279,8 @@
   {
     # <remarks>Exit early if existing system file cannot be overwritten.</remarks>
     if [[ -e "${PATH_1}" ]] \
-      && ! sudo rm -f "${FILE_1}" &> /dev/null; then
-      echo -e "${PREFIX_ERROR} Failed to delete file '${FILE_1}'."
+      && ! sudo rm --force "${FILE_1}" &> /dev/null; then
+      print_to_error_log "Failed to delete file '${FILE_1}'."
       exit 1
     fi
   }
@@ -252,15 +289,17 @@
   {
     # <remarks>Exit early if system directory does not exist and cannot be created.</remarks>
     if [[ ! -d "${PATH_1}" ]] \
-      && sudo mkdir -p "${PATH_1}"; then
-      echo -e "${PREFIX_ERROR} Failed to create directory '${PATH_1}'."
+      && sudo mkdir --parents "${PATH_1}"; then
+      print_to_error_log "Failed to create directory '${PATH_1}'."
       exit 1
     fi
   }
 
   function match_driver_and_set_xorg_write_only
   {
-    case "$_DRIVER" in
+    local -r driver="${1}"
+
+    case "${driver}" in
       *"nouveau"* )
         MATCH_PROBLEM_DRIVER=true ;;
     esac
@@ -268,73 +307,74 @@
 
   function match_valid_vga_device_with_driver
   {
-    if [[ "$_DRIVER" == "" || "$_TYPE" == "" || "$_VENDOR" == "" ]]; then
-      echo -e "Found Driver: 'N/A'"
+    if ! is_string "${driver}" &> /dev/null \
+      || ! is_string "${type}" &> /dev/null \
+      || ! is_string "${vendor}" &> /dev/null; then
+      print_to_output_log "Found Driver: 'N/A'"
       return 1
     fi
 
-
-    if ( [[ "$_TYPE" =~ ^"vga" ]] \
-      || [[ "$_TYPE" =~ ^"graphics" ]] ) \
-      && ! [[ "$_DRIVER" =~ ^"vfio-pci" ]]; then
-      local _PREFERRED_VENDOR=""
-      match_vendor_and_override_driver
-
-      # <remarks>Print</remarks>
-      echo -e "Found Driver: '$_DRIVER'"
-
-      # <remarks>Set evaluation if a preferred driver is given.</remarks>
-      if ! "$PREFER_ANY_BRAND"; then
-        get_preferred_vendor
-        return "$?"
-      fi
-
-      return 0
+    if ( ! [[ "${type}" =~ ^"vga" ]] && ! [[ "${type}" =~ ^"graphics" ]] ) \
+      || ! [[ "${driver}" =~ ^"vfio-pci" ]]; then
+      return 1
     fi
 
-    return 1
+    local preferred_vendor=""
+    match_vendor_and_override_driver "${preferred_vendor}" "driver"
+    print_to_output_log "Found Driver: '${driver}'"
+
+    if ! "${PREFER_ANY_BRAND}"; then
+      get_preferred_vendor "preferred_vendor" "${vendor}"
+      return "${?}"
+    fi
   }
 
   function match_vendor_and_override_driver
   {
-    case "$_VENDOR" in
-      *"intel"* )
-        if [[ "$HAS_MATCHED_INTEL_DRIVER" == true ]]; then
-          _DRIVER="modesetting"
-        else
-          echo -e "${PREFIX_NOTE} Should given parsed Intel VGA driver be invalid, replace xorg.conf with an alternate intel driver (example: 'modesetting')."
-        fi ;;
+    local -r vendor="${1}"
+    local -n reference="${2}"
 
-      * )
-        ;;
+    case "${vendor}" in
+      *"intel"* )
+        override_intel_vga_driver "${reference}" ;;
     esac
+  }
+
+  function override_intel_vga_driver
+  {
+    local -n reference="${1}"
+    local -r override_driver="modesetting"
+
+    if "${HAS_MATCHED_INTEL_DRIVER}"; then
+      reference="${override_driver}"
+    else
+      print_to_output_log "Should given parsed Intel VGA driver be invalid, replace xorg.conf with an alternate intel driver (example: '${override_driver}')."
+    fi
   }
 
   function restart_service
   {
-    # <remarks>Restart system service automatically or manually.</remarks>
     if "${DO_RESTART_DISPLAY_MANAGER}" \
-      && ( ! sudo systemctl enable "${FILE_2}" \
-        || ! sudo systemctl restart "${FILE_2}" ); then
-      echo -e "${PREFIX_ERROR} Failed to restart system service."
+      && ( ! sudo systemctl enable "${FILE_2}" || ! sudo systemctl restart "${FILE_2}" ); then
+      print_to_error_log "Failed to restart system service."
       exit 1
     fi
   }
 
   function set_file
   {
-    case "$?" in
+    case "${?}" in
       0 )
         FILE_1_CONTENTS+=(
           ""
           "Section    \"Device\""
           "   Identifier  \"Device0\""
-          "   Driver    \"$_DRIVER\""
-          "   BusID     \"PCI:$_PCI_ID\""
+          "   Driver    \"${driver}\""
+          "   BusID     \"PCI:${pci_id}\""
           "EndSection"
         )
 
-        echo -e "$PREFIX_PASS Valid VGA device found."
+        print_to_output_log "Valid VGA device found."
         ;;
 
       * )
@@ -347,43 +387,36 @@
           "EndSection"
         )
 
-        echo -e "$PREFIX_FAIL No valid VGA device found."
+        print_to_error_log "No valid VGA device found."
         ;;
     esac
 
-    IFS=$'\n'
-    echo -e "${FILE_1_CONTENTS[*]}" >> "${FILE_1}"
-    EXIT_CODE="$?"
-
-    if [[ "${EXIT_CODE}" -ne 0 ]]; then
-      echo -e "${PREFIX_ERROR} Failed to write to file '${FILE_1}'."
+    if ! echo -e "${FILE_1_CONTENTS[*]}" >> "${FILE_1}"; then
+     print_to_error_log "Failed to write to file '${FILE_1}'."
+      return 1
     fi
-
-    return "${EXIT_CODE}"
   }
 
   function toggle_sort_order_of_devices
   {
-    # <remarks>Toggle the sort order of parse of PCI devices.</remarks>
     if "${PARSE_PCI_ORDER_BY_BUS_ID}"; then
-      declare -ga _HWID_LIST=( $( eval ${GET_PCI_ID} ) )
+      HWID_LIST=( $( eval "${GET_PCI_ID}" ) )
     else
-      declare -ga _HWID_LIST=( $( eval ${GET_PCI_ID_REVERSE_SORT} ) )
+      HWID_LIST=( $( eval "${GET_PCI_ID_REVERSE_SORT}" ) )
     fi
   }
 
   function write_to_file
   {
-    # <remarks>Write to file if directory exists and driver is valid.</remarks>
     if [[ ! -d "${PATH_1}" ]]; then
       echo -e "${PREFIX_ERROR} Failed to create directory '${PATH_1}'."
       exit 1
     fi
 
     if ! "${MATCH_PROBLEM_DRIVER}"; then
-      set_file || exit "$?"
+      set_file || exit "${?}"
     else
-      echo -e "${PREFIX_NOTE} Not writing to file given presence of problem driver."
+      print_to_output_log "Not writing to file given presence of problem driver."
     fi
   }
 # </functions>
